### ISSUE TITLE
Support Edge/Opera Store

### ISSUE THREAD

**Issue by dtantono** [joelacus/RedditEnhancer#1]
Hi
I know on homepage that Chrome extension support is coming soon. But, I hope Edge/Opera store can be supported as well. What do you think?

**Comment by joelacus** [comment]
Sure, it should be a similar process for those browsers, I'll add it to my to do list

**Comment by joelacus** [comment]
Hi, the Chrome version is still in review, but it is now available on the Edge store. I'll do Opera soon.

**Comment by joelacus** [comment]
It doesn't seem Opera review new extensions anymore, as I haven't received a response in over four months. Lots of other developers have reported a similar experience. This extension fortunately can be installed from the Chrome store instead, so I'm going to mark this issue as closed.
