### ISSUE TITLE
Remember comments sort option

### ISSUE THREAD

**Issue by Mystqr4** [joelacus/RedditEnhancer#10]
Under the new redesign the comments are set to sort by "Best" which is not always... well... best and usually results in the natural flow of the conversation being out of order and not make much sense. 
Is there a possibility to have an option to remember sort options on comments or rather set a default sorting option other than "Best". 

On a side note I have noticed that the sidebars on the right are still around when I go to a users post. I'm not sure if I have missed an option to hide them but I don't see the need for them to be around there either.

Thanks.

**Comment by joelacus** [comment]
I could add a feature to set a default sort option. That should be pretty straight forward.
Regarding the sidebar, do you mean the post sidebar when you have the post open in its own tab, or when you click on it from the feed and it shows the post as a popup over the feed? Currently, hiding the post sidebar will only hide it when the post is open in its own dedicated tab.

**Comment by Mystqr4** [comment]
That would be really cool. I don't know why they removed the ability to set a default sorting scheme. It would be really amazing if you could.
Yeah, I guess I was referring to the post popup over the feed. I could probably deal with it still being there so that is fine.

It's a pretty neat extension. I'm looking forward to seeing what the future may bring.

**Comment by joelacus** [comment]
Hi. I've just published version 0.15.0. You can now set the default sort option for the comments section, as well as the feed. For the comments section however, it only works when you open the post in its own tab/window. I'll see if I can figure out how to set a default option when you open a post in the feed overlay. The update is out now for Firefox, but will take about a week for Chrome and Edge to process it. Btw, hiding the post sidebar will now also hide it on the  feed overlay. :)
