### ISSUE TITLE
Changing font size incorrectly changes line height

### ISSUE THREAD

**Issue by Domiran** [joelacus/RedditEnhancer#103]
Unsized:
![image](https://github.com/user-attachments/assets/e9e6a755-e620-49da-a52c-0d6dd8ce71ba)

Size-matched, using the Accessbility Post Title slider:
![image](https://github.com/user-attachments/assets/df0e4683-5c4c-43f4-9b5b-3137b752a3ca)

Any letter that goes below the line is cut off.

This happens on Firefox 135 (Nightly) and 133.

**Comment by joelacus** [comment]
This is the same issue as [#97](https://github.com/joelacus/RedditEnhancer/issues/97). It will be fixed in the next update :)

**Comment by Domiran** [comment]
Ah, my search-fu was not good enough. Should I close this?

**Comment by joelacus** [comment]
No worries. I'll close it when I publish the update.
