### ISSUE TITLE
[Feature Request] Change comment controls text color?

### ISSUE THREAD

**Issue by Domiran** [joelacus/RedditEnhancer#104]
I really struggle with what makes this 3rd version of Reddit harder to read for me. Is it possible to add something to change the color of the comment controls?

![image](https://github.com/user-attachments/assets/91238f4e-5b39-4ab0-8f5b-975c462c04c5)

I feel like "change font" might be next. Maybe it's just me but Reddit now seems to hurt my eyes.

**Comment by joelacus** [comment]
Changing the "Style" > "Post: Comments Text Colour" option will also change the action row text colour, but I'll see if I can separate the action row colour into its own option.

I've thought about adding a way to use custom fonts. I'll see what I can do.

**Comment by joelacus** [comment]
I've added a new option in version 1.13.0 to change the action row colour.
Style > Post > "Post: Comment Action Row Colour"
