### ISSUE TITLE
[Feature Request] Post numbering for new reddit

### ISSUE THREAD

**Issue by WerDei** [joelacus/RedditEnhancer#12]
Old reddit has a feature where it numbers the posts:
![image](https://github.com/joelacus/RedditEnhancer/assets/48105614/8a6fd67d-0db0-49f8-999e-871a9cfadb18)

It's a useful tool for self control, and I'd love to have it in a new design.

**Comment by joelacus** [comment]
That's a good idea actually. I'll see what I can do :)

**Comment by joelacus** [comment]
Hi. I've just published version 0.16.0 with this feature. It's enabled by default. You should get the update automatically within a few days.
