### ISSUE TITLE
[Feature Request] Disable popup asking to turn on notifications for a sub

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#17]
<img width="282" alt="image" src="https://github.com/joelacus/RedditEnhancer/assets/4202657/5cba6eca-f5c1-401c-8b1b-6567efd1dd5e">

Any chance this popup can be disabled on every subreddit?

**Comment by joelacus** [comment]
Hey. Yeah, I'm actually working on a new update now, this I think will be pretty simple to add to it. Sorry I haven't added your other feature request yet, I had a bit of trouble with that one, I'll retry soon.

**Comment by joelacus** [comment]
I've just published version 0.16.0 with an option to hide this. You'll have to enable it (Hide Elements > Hide "Get the best of" Popup). You should have the update automatically within a few days.

**Comment by gh0sti** [comment]
thanks for the fix
