### ISSUE TITLE
[Bug] Show navigation buttons clicking top arrow doesn't do anything

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#18]
With navigation buttons enabled clicking the down arrow works to go to the next root comment. Clicking the top arrow doesn't bring you back to the previous top root comment. New Reddit interface.

info: 
Brave Browser [Version 1.53.108 Chromium: 115.0.5790.56 (Official Build) (x86_64)]
macOS 13.4.1 intel

**Comment by joelacus** [comment]
Is that when you have the post open in its own tab/window? I know this feature doesn't work on the post overlay on the feed, but I have just fixed that in a new update (not published yet).

**Comment by gh0sti** [comment]
yea post open in its own tab window

**Comment by joelacus** [comment]
I've just tested in Brave and I did notice the up didn't work a couple times. I'm not sure why, but the update I made to support the post overlay I think may have fixed this issue. I've published 0.16.1. It'll take a few days to be approved, but let me know if you still have the issue, or hopefully this fixed it!
