### ISSUE TITLE
Feat: Expand the Image too

### ISSUE THREAD

**Issue by alok1nanda** [joelacus/RedditEnhancer#19]
The ability to make images go wider

**Comment by joelacus** [comment]
Hi. I could add an option to change the image width, but it would mean the bottom of the image will be cut off, so I'd have to add a scroll bar. By default, the max height of a post is 512px, I could add another option to change this however so you can see more of the image.

**Comment by joelacus** [comment]
I've just published version 0.17.0 with a new feature called "Feed Post Max Height". This will allow posts to expand vertically to a larger size, and the images will adapt to the new size. If you combine this with the "Expand Feed/Post" feature, you can get larger images on posts :)
