### ISSUE TITLE
Inconsistency Between Edge and  Firefox version

### ISSUE THREAD

**Issue by dtantono** [joelacus/RedditEnhancer#2]
Hello
I know the edge version have been released. But, I noticed there are bugs on Edge version. what do you think?

Reddit for Edge
![image](https://user-images.githubusercontent.com/29157187/219223872-92e2d621-c17c-440b-9346-d86ded20e8ea.png)

<img width="927" alt="Snipaste_2023-02-16_08-28-33" src="https://user-images.githubusercontent.com/29157187/219216213-be0d40d6-3b79-4dda-b054-dcb664860948.png">
Reddut for Firefox
<img width="943" alt="Snipaste_2023-02-16_08-28-16" src="https://user-images.githubusercontent.com/29157187/219216225-d155be6d-0543-4edc-ab2a-7c1b332b34ce.png">
I make same parameters between those extensions
<img width="351" alt="Snipaste_2023-02-16_08-27-39" src="https://user-images.githubusercontent.com/29157187/219216236-fe395690-6d05-413a-9aed-a4d9cd5356a8.png">

**Comment by joelacus** [comment]
Hi. I've submitted version 0.4.0 to Edge today, the same version as Firefox now, but it's still in review, so will take a couple days to go live. That particular feature however, should work the same on either version. Have you refreshed the Reddit page since installing the extension on Edge?

**Comment by dtantono** [comment]
yeah, same result. it looks bad on Edge

**Comment by joelacus** [comment]
I'm not sure. I can't replicate the issue myself. I've just tested it with Edge version 110.0.1587.41.
Have you set the Width to a higher value in the "Expand Feed / Post" sub menu?

**Comment by dtantono** [comment]
yeah it works. But, i noticed on Firefox there is extra tweaks menu. But, on Edge I got nothing. So, I think the Edge version will be updated soon right?

**Comment by joelacus** [comment]
Good. And yes, I'll try to keep all browsers on the same add-on version, but Firefox is faster to approve my updates, Chrome and Edge will just be a few days behind. Eventually they will all get the same features.
