### ISSUE TITLE
Hide the Header

### ISSUE THREAD

**Issue by looloo86** [joelacus/RedditEnhancer#26]
Is it possible to completely hide the header at the top for a more immersive view? Or have it stay at the very top so that it doesn't follow you as you scroll down?

**Comment by joelacus** [comment]
Hi. Yes, both options are possible! I can add these in the next update.

**Comment by looloo86** [comment]
Thank you! Looking forward to it. And speaking of hiding things, is it also possible to hide the "Back to Top" button on the lower right side?

**Comment by joelacus** [comment]
Yeah, I should be able to do that as well.

**Comment by looloo86** [comment]
Great, thanks again! Do you know when you will release the new update?

**Comment by joelacus** [comment]
Maybe within a couple weeks, I'm not sure. I'm just finishing off an update for another project at the moment, then I'll work on this one again.

**Comment by joelacus** [comment]
Hi. I've just published version 0.19.0 with options to hide the header bar, make it not sticky so it doesn't follow you as you scroll, and also an option to hide the original scroll to top button. It's out now for Firefox, and Chrome and Edge will update soon :)
