### ISSUE TITLE
[Suggestion] Option to use the default New Reddit post view when clicking on posts

### ISSUE THREAD

**Issue by Void48** [joelacus/RedditEnhancer#27]
Hey, I appreciate you for creating this extension! The only thing I dislike is that when I click on posts now, they open in full view, and I can't click on the sides to go back to scrolling through new posts
**With extension installed:**
![image](https://github.com/joelacus/RedditEnhancer/assets/85196642/27213b88-bd08-470d-bd23-5900afd7fa40)
**Default post view without extension installed:**
![image](https://github.com/joelacus/RedditEnhancer/assets/85196642/7f74d7ab-730c-4cd6-84d1-930914e5311b)

**Comment by joelacus** [comment]
Hi, thanks for the feedback! This was a difficult feature to implement with how new reddit works, but I'll have a look into it again and try to make some improvements :)

**Comment by joelacus** [comment]
Hi. These issues should be fixed in version 0.20.1 :)
