### ISSUE TITLE
[Feature Request] Adjust Classic threads height

### ISSUE THREAD

**Issue by thesoloist-1** [joelacus/RedditEnhancer#28]
Not sure if it is possible but would be a nice addition if we could adjust the height of the classic threads posts along with the thumbnails. I prefer using classic view but currently the height is quite small and hard to read.
![Screenshot 2023-09-27 at 7 22 12 AM](https://github.com/joelacus/RedditEnhancer/assets/97246028/30f3665b-30fa-4f23-8e6b-d7ed75e320fa)
Below is an example from kbin with a bit of an exaggerated height. 
![Screenshot 2023-09-27 at 7 22 32 AM](https://github.com/joelacus/RedditEnhancer/assets/97246028/438cd5ed-84e4-4948-8aec-93118a60e1b3)

**Comment by joelacus** [comment]
Hi. Yeah I can add this, it does look nicer in that example.

**Comment by joelacus** [comment]
I've just published version 0.20.0 with an option to enable 'Larger Classic Post View' under the 'Style' section. The update will be available soon :)

**Comment by thesoloist-1** [comment]
Perfect. Thanks dude
