### ISSUE TITLE
Feature Request: Add settings for New New Reddit

### ISSUE THREAD

**Issue by valantur** [joelacus/RedditEnhancer#29]
Reddit looks different (again) and it would be great if future developement adds custominzation options for the new look:

<img width="1111" alt="reddit new look" src="https://github.com/joelacus/RedditEnhancer/assets/2516392/7dc26613-c1c6-4c7d-b30e-485eb426f02d">

**Comment by joelacus** [comment]
I've been dreading this haha. I think this new new UI is only for when you're not logged in, and when you are logged in it uses the old new UI, but I guess eventually they will switch everyone to it, so I should be prepared for that.
I'll have to find a way to detect which UI reddit is using, and then modify the features to work with it.
It may take a while to get every feature working, but I will make a start on it.

**Comment by joelacus** [comment]
I've just finished working on another project, so I can now turn my attention back to this one.

"new.reddit.com" and "sh.reddit.com" is good to know thanks, I could add an option in the extension to redirect to whichever version the user prefers. 

New changes can be frustrating. I can't make a mobile app, but I can help with option 3 for sure. I'll have to reverse engineer the new new codebase though to rewrite the extension features to support it. Although looking at the code, it seems easier to work with than the previous version. I'll try to support all relevant features for the new new version, and if there are any features specificity for the new new version you can think of, let me know.

I've not used the new new version much, but it feels a bit more lightweight than the previous version which is good at least. I still need to play with it more though to see how the UI/UX has changed, for the better or worse!

**Comment by DejayRezme** [comment]
> Although looking at the code, it seems easier to work with than the previous version. 

Well that is good news! Reddit also seems to actively work on issues: https://sh.reddit.com/r/help/comments/18igcrp/addressing_mobile_web_feedback/

My personal main gripe is the comment editor box, they don't respect the "Default to markdown" option in preferences. Hopefully reddit will fix it. I wish reddit would implement something similar to Typora or MarkText, there is no reason to do it this badly.

Another thing is that when zooming in the new.reddit looses the sidebar at 140% zoom while sh.reddit looses the sidebar at 170%. That depends on your browser size and window scale of course. 
So an option to toggle the sidebar would be awesome. That would help with the rather biggish appearance. And some options to change font sizes, and the toxic dark green they use as a dark mode.

**Comment by joelacus** [comment]
Hey, sorry this has taken a while, but I've just published a new update, and it's a big one!
Most of the features now support New New Reddit! I still have a few more to work on, but I thought I should release what I've already done now. 

I've also added an option to auto redirect pages to Old, New or New New Reddit. (top right of the extension). I've noticed however, if you are not logged in, Reddit will insist you use the New New version, even with "new.reddit.com". So this will fight the extension and you'll get stuck in a loop! I'll see if I can find a way to break it. Seems to work fine though if you are logged in, for now at least.

I don't think I can fix the "Default to markdown" option sorry, it seems like a bug Reddit has to deal with I'm afraid. However, toggling all the sidebars, and the sidemenu is supported now, and you can change the post and comment font sizes in the new Accessibility section. I still have some more colour options to add, but you can change the header bar and post colours for now. See the changelog in the extension or this repo for all the changes.

I'll close this issue now, but please feel free to open a new issue if you find any problems, or think of anything else I can add in the next version, thanks! :)
