### ISSUE TITLE
[Feature Request] Always show rising button

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#3]
Any chance we can have on new.reddit.com the rising button always shown instead of hidden in the ellipse? I find that design/option such a stupid option that they hide it in the ellipses and that's all they hide there.

![image](https://user-images.githubusercontent.com/4202657/220391463-7bf16f63-0377-4430-8e1f-f3c8682e2f3b.png)

![image](https://user-images.githubusercontent.com/4202657/220391542-1bfc127b-75fa-4c42-8b90-d4ac219149e9.png)

![image](https://user-images.githubusercontent.com/4202657/220391579-d221a684-a1c4-48e5-b33c-b249d9d44458.png)

**Comment by joelacus** [comment]
Hi, yeah I agree, it is a stupid design. I'll try to add this to the next version.

**Comment by gh0sti** [comment]
> Hi, yeah I agree, it is a stupid design. I'll try to add this to the next version.

Thanks appreciate it!

**Comment by joelacus** [comment]
Hey, I've just uploaded a new update with this feature! It's enabled by default. If you're on Firefox, the update is out now, but if you're on Chrome or Edge it will take up to a week or so to be approved and then released. :)
