### ISSUE TITLE
[Bug] Scroll to Top Button Not Working

### ISSUE THREAD

**Issue by depleur** [joelacus/RedditEnhancer#30]
- **Steps to Reproduce**:
  1. Open a post on Reddit using the Firefox extension.
  2. Attempt to use the scroll to top button.
  
- **Expected Behavior**: The scroll to top button should smoothly scroll to the top of the page.

- **Actual Behavior**: Nothing happens.

- **Additional Information**:
  - Extension Version: 0.19.0
  - Browser Version: Firefox Version 118.0.2 (64-bit)

**Comment by joelacus** [comment]
Thanks! I've fixed this and it will be in the next update. The scroll to top button now detects if the post overlay is open and will scroll to the top of that, otherwise it will scroll the main page to the top.
