### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by onionringostar** [joelacus/RedditEnhancer#31]
Can you add an option to turn off the these line breaks, I want this part to be in the original format

pic 1:

![Untitled](https://github.com/joelacus/RedditEnhancer/assets/152268834/17f64886-a8c0-4d0b-86cc-80b121ef1c34)

the break in the line as circled

Original reddit: 

![image](https://github.com/joelacus/RedditEnhancer/assets/152268834/d87440de-e8ca-4008-b894-d6a162ff059d)

**Comment by joelacus** [comment]
Hi. This is just a bug, thanks for letting me know! This will be fixed in the next version :)

**Comment by onionringostar** [comment]
Great, thanks for the reply.

This is on the Edge version ftr
