### ISSUE TITLE
[Feature Request] different width setting for feed, subreddit, and post

### ISSUE THREAD

**Issue by dmt0** [joelacus/RedditEnhancer#34]
What an awesome plugin! My life will never be the same!

Would be great if we could have separate width controls for feed, subreddit, and post. 
Main reason: I wanna be able to block a sidebar on one of those and not the others, in that case the width becomes very different.

<img width="1792" alt="image" src="https://github.com/joelacus/RedditEnhancer/assets/2717746/b1d75b11-b1c6-426a-982e-88d4a3fecb70">
<img width="1792" alt="image" src="https://github.com/joelacus/RedditEnhancer/assets/2717746/04326bfa-9f46-4513-a34d-9faf89cae07c">

(This can be mitigated by simply not changing width, but then the width setting becomes kinda useless)

**Comment by joelacus** [comment]
Thanks! I'm glad you like it :)

Ah I see the problem, yes, that's a good point. I'll add these controls in the next version.

**Comment by joelacus** [comment]
Hi. I've just published a new update! You can now individually control the width of the home feed, subreddit feed, user profile feed, post page and the post overlay. I've made a lot of changes in this update, everything should apply instantly when you load a page. This feature now also works on the latest version of Reddit! Let me know if you have any other issues. Thanks!
It's available now for Firefox. Chrome and Edge may take a few days to process.
