### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Looodon** [joelacus/RedditEnhancer#35]
Hey! 
I would like to know what the privacy policy is. Does any of the data leave my browser or is it all local?
Thanks!

**Comment by joelacus** [comment]
Hi. That's a fair question, I should make a note of that somewhere actually. 

Only the settings you choose in the extension are saved, and are only saved locally in your browser. If you are logged into your Firefox, Chrome or Edge account however and have browser sync enabled, then the saved settings data will be synced to your other devices, but this is all handled by the browser.

The two permissions the extension requires from your browser are "Storage" and "Tabs".

"Storage" simply allows the settings to be saved and restored. It can only read and write to its own storage and has no access to anywhere else.

"Tabs" allows the extension popup with the settings to communicate with any open reddit.com tabs to apply the features/tweaks on the page. Here is an example of how it is used:

```
browser.tabs.query({ currentWindow: true }, function (tabs) {
	tabs.forEach(function (tab) {
		if (tab.url.includes('reddit.com') && tab.discarded == false) {
			browser.tabs.sendMessage(tab.id, { expandLayout: true });
		}
	});
});
```

Furthermore, the script which listens for and applies the tweaks can only run on reddit.com.

I'll add a privacy policy section to the readme soon. I hope this helped. Let me know if you have any other questions :)

**Comment by joelacus** [comment]
I've added a Privacy Policy section to the end of the readme.
