### ISSUE TITLE
Line is split and hard to click

### ISSUE THREAD

**Issue by romskidd** [joelacus/RedditEnhancer#36]
Hi,

I love the extension but this drives me crazy, the lines on the left is split and is really hard to click to toggle posts, is it an error from me or something I can fix myself ? (Using Firefox, latest update)

Example: https://i.imgur.com/F6C6mPa.png

Thanks!

**Comment by joelacus** [comment]
Ah yeah, sorry about that. This is a known bug and I've already fixed it for the next version. This next version is pretty big so it's taken a little longer to release, but should be out in a week or so!

Other than this issue, I'm happy you love the extension :)

**Comment by romskidd** [comment]
Awesome thank you, can't wait to see that update!
