### ISSUE TITLE
[Feature Request] Font colour for comments and more dark options

### ISSUE THREAD

**Issue by SullieLore** [joelacus/RedditEnhancer#39]
I'd like to recommend:

1. Add font colour options; I found a way around this by using bionic and then changing the colour, but it isn't ideal as I don't really want to use bionic for comments.

2. Dark mode has a lot of bright white elements, such as the text for the About Community sections and most of the right side panel with subreddit rules etc. It would be good to have options to reskin these to dark/not white text.

Great extension overall.

**Comment by joelacus** [comment]
Hi. Yes, I can add more style options, no problem.

Thanks :)

**Comment by joelacus** [comment]
I've just published version 1.1.0 with options to change the comments text colour, the sidebar text, background and border colours, and the sidemenu text and background colours. Let me know if there are any other style options you'd like to have and I'll try to add them! :)
