### ISSUE TITLE
[Feature Request] Always show buttons hidden behind ellipses  

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#4]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/4202657/222907317-79edfa07-d023-4043-aba6-1382b681eecd.png">

Thanks for implementing the always show rising button. Can the next feature be always show save and other buttons in a comment feed?

**Comment by joelacus** [comment]
You're welcome :) Yeah, I can add this to my to-do list.

**Comment by gh0sti** [comment]
Just bumping this.

**Comment by gh0sti** [comment]
@joelacus thank you for all your hard work hoping this feature can be added in the future.

**Comment by joelacus** [comment]
I've tried again to get this working, but I'm a bit stuck at the moment sorry. I can move the buttons from the dropdown menu next to the other buttons fine, but then the buttons don't work anymore. I'm not sure why, as the buttons still have the event listeners intact. I'll continue to try though :/

**Comment by gh0sti** [comment]
> I've tried again to get this working, but I'm a bit stuck at the moment sorry. I can move the buttons from the dropdown menu next to the other buttons fine, but then the buttons don't work anymore. I'm not sure why, as the buttons still have the event listeners intact. I'll continue to try though :/

that's silly that reddit is not cooperating.

**Comment by gh0sti** [comment]
> I've tried again to get this working, but I'm a bit stuck at the moment sorry. I can move the buttons from the dropdown menu next to the other buttons fine, but then the buttons don't work anymore. I'm not sure why, as the buttons still have the event listeners intact. I'll continue to try though :/

any updates to this by chance?

**Comment by joelacus** [comment]
> any updates to this by chance?

Not for the "Old New" UI unfortunately, sorry, but I've managed to get it working for the latest version. The new update (v1.3.0) should be out soon.

**Comment by joelacus** [comment]
Sorry I never got this working for the Old New UI, but since Reddit has discontinued this version now and this feature works with the latest version, I'll close this issue.
