### ISSUE TITLE
[Feature Request] Hide 'hidden posts'

### ISSUE THREAD

**Issue by kield** [joelacus/RedditEnhancer#41]
![image](https://github.com/joelacus/RedditEnhancer/assets/62976111/383e722a-5ba9-481d-8805-ec8ac2a3cb89)

An option to hide these useless things?

**Comment by joelacus** [comment]
Yeah no problem, I can add this in the next version.

**Comment by joelacus** [comment]
Hi. I've just published version 1.1.0 with a "Hide 'Post Hidden' Message" option :)
