### ISSUE TITLE
BUG- For New New UI Home Feed cannot be expanded fully

### ISSUE THREAD

**Issue by dtantono** [joelacus/RedditEnhancer#43]
Hi
I tried to expand the bar on the home feed screen and it does not work. But, when I checked the subreddit feed. it works properly. What do you think?
![2024-02-27_08-20](https://github.com/joelacus/RedditEnhancer/assets/29157187/524632af-af1e-42eb-b70d-7e83b73d94b0)

![2024-02-27_08-26](https://github.com/joelacus/RedditEnhancer/assets/29157187/40c444da-9b2a-4a05-9fd8-c0db3df8ea3c)
![2024-02-27_08-25](https://github.com/joelacus/RedditEnhancer/assets/29157187/3966490b-d245-438c-9669-12029a1d32a9)

**Comment by joelacus** [comment]
It works for me, but I don't see "Recent Posts", maybe that is causing it to break? I'll try to fix this, but in the meantime, does it work if you clear the recent posts?

**Comment by dtantono** [comment]
Like this one, I find this on newest post 
![2024-02-29_11-47](https://github.com/joelacus/RedditEnhancer/assets/29157187/dc59b996-6f29-46f1-ad92-73b9e60bfeb2)
![2024-02-29_11-46](https://github.com/joelacus/RedditEnhancer/assets/29157187/be701af3-58ae-4715-ba22-e8d43b792013)

**Comment by joelacus** [comment]
Hi. I figured it out and fixed this issue. The blank space there is actually an empty sidebar, usually with a couple ads in it. 
If you have an ad blocker installed, it will hide the ads, but not the sidebar. 
I didn't realise this before and just hid the blank space for the resize feed feature, but that only worked for windows/screens equal to or greater than 1920p. If you have a smaller window/screen, the blank space would reappear, therefore preventing you from making the content wider. 

I'll upload the new version soon (v1.3.0). There will be a new option to hide the home feed sidebar for New New UI.
Enabling this should then fix the issue. Once you get the update and try it, let me know if it works and I'll close the issue.
Thanks :)
