### ISSUE TITLE
(Feature Request) for Default Feed and Sort option for New New Reddit

### ISSUE THREAD

**Issue by dtantono** [joelacus/RedditEnhancer#45]
Hi
I know new.reddit.com we can ge this feature. Can you add this feature for new new reddit UI?
![2024-03-05_12-44](https://github.com/joelacus/RedditEnhancer/assets/29157187/57c29a58-77d9-4da9-9330-57fdc77e4531)

**Comment by joelacus** [comment]
Hi. Yeah I can add this.

**Comment by joelacus** [comment]
I've just published version 1.5.0 with this :)
