### ISSUE TITLE
Bring back the colours of the Reddit Enhancer Menu UI from the 1.2.0 version

### ISSUE THREAD

**Issue by sliceanddice9** [joelacus/RedditEnhancer#46]
![reddit enhancer add on old version of ui menu vs new version of ui menu 1](https://github.com/joelacus/RedditEnhancer/assets/59092472/16e73f02-72f4-4a01-996c-75028bc5d51a)
![reddit enhancer add on old version of ui menu vs new version of ui menu 2](https://github.com/joelacus/RedditEnhancer/assets/59092472/a34e1f60-3448-4e16-9f04-f5d54f9bbb9d)

In the default 'light mode' the colour scheme of the 1.2.0 version is better on the eyes when compared to the latest 1.3.0 version IMO. The whites and transparency levels of the buttons, icons, slider bars and switches just don't look as aesthetically pleasing, and thus makes navigation a little more difficult. I'm not a fan of 'dark mode' in general so I rather not enable that setting.  

As for the positives - the 1.3.0 version is more compact, and I like that the placement of the 'backup', 'restore' and 'english' buttons don't overlap anymore, so they are more neatly formatted/aliened. 

Could we get an update that incorporates the colour scheme of the 1.2.0 version but with the compact and cleaner layout of the 1.3.0 version?

**Comment by joelacus** [comment]
Ah, sorry. I thought the old light theme was a bit too dull. I can tweak the new light theme, but I'll also add an option to use the old light theme. I'll add a new settings page like this where you can choose the theme:
![image](https://github.com/joelacus/RedditEnhancer/assets/43767965/b021d0f3-6d16-4d33-bcde-df926885a76e)

**Comment by sliceanddice9** [comment]
Sounds good thank you!

**Comment by joelacus** [comment]
I've just published version 1.4.0 with this new settings page and classic light theme option.
