### ISSUE TITLE
[Feature Request] Clicking on the /r/shortcut to open in new tab instead of current tab

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#5]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/4202657/222915060-7dd87b16-57d4-4411-b193-ff2d2e0ad5fe.png">

old reddit on homepage when clicking on the link /r/subreddit it will open in a new tab. New reddit which is stupid does not do this. When on the homepage clicking on a subreddit shortcut under a post just opens in current tab. Can we have it where clicking on the /r/sub will open in a new tab?

**Comment by joelacus** [comment]
Yeah I can implement this.

**Comment by joelacus** [comment]
Hi, this feature is now in version 0.7.1! The update for Firefox is out now, Chrome and Edge will be another week or so. You will need to enable the option in Reddit Enhancer > Productivity > Open Links To Sub Reddit In New Tab. Or simply search for "tab" in the new search filter :)
