### ISSUE TITLE
[BUG] Blurred when turning on color in posts

### ISSUE THREAD

**Issue by RedAstaire1** [joelacus/RedditEnhancer#50]
I don't know if you can see well on the screen. On the left, custom color enabled, on the right, no.
![FLOU](https://github.com/joelacus/RedditEnhancer/assets/74464658/9057d865-4616-481d-8943-4f008b8eec3b)

Maybe it's a fault of Edge, I use Edge, not chrome. 

And I'm using the chrome store one, the microsoft store one is version 1.4.0, the chrome store one is 1.5.0

I tried it with Vivaldi, and it doesn't have this blurry effect... weird

**Comment by RedAstaire1** [comment]
Ok, it's the option "Try the new look and feel of Microsoft Edge" that causes problems, disabling it no more worries

**Comment by joelacus** [comment]
Hi. Do you mean the text or the background? Using custom translucent colours for the post background will show the blur effect, this can be disabled (Theme Blur). 

> Ok, it's the option "Try the new look and feel of Microsoft Edge" that causes problems, disabling it no more worries

I only use Edge for testing, I'm not sure what this feature does. If disabling this fixes the issue, cool. I'll see if I can find that option and replicate the issue and figure out what is happening.

> And I'm using the chrome store one, the microsoft store one is version 1.4.0, the chrome store one is 1.5.0

I upload the updates for Firefox, Chrome and Edge at the same time, but Microsoft takes about a week longer to process the updates unfortunately. They are more or less the same package though.

Btw, do you speak French? I'm just curious how the French translation is for the extension if you use it, any errors?
I only know a little, so had to use Google Translate and ChatGPT, so I hope it's ok! :)

**Comment by joelacus** [comment]
> Yes, the French translation is pretty good, maybe the traduction of "Show Post Flair on the home feed" , which should instead be translated as "Montrer les Flair des postes" rather than "Spectacle 'Post Flair' " ;)

Ah yes, merci beacoup :)

I've found the "Try the new look and feel of Microsoft Edge" option in Edge, but it doesn't seem to do anything for me. I'm curious what it does though. Have you tried changing the font colour to white? Maybe that will make it look sharper.

> I tried it with Vivaldi, and it doesn't have this blurry effect... weird

I just realised, I guess you used the Chrome version for Vivaldi? Does it work well? I can add it as a supported browser.

**Comment by RedAstaire1** [comment]
![Capture d'écran 2024-04-06 151404](https://github.com/joelacus/RedditEnhancer/assets/74464658/ed740286-d6a1-4667-b288-ba010e661097)

No, I didn't try to put the font in white.

The theme rounds the corners of web pages. It's very subtle and light, which causes a slight reduction in the size of the page, on the order of a few pixels. I have a resolution of 1920x1080, maybe that's playing. 

For Vivaldi, I use it very little today, if at all. I wasn't even aware that there was another version of Vivaldi today that wasn't based on Chromium.
