### ISSUE TITLE
Extension changing default font size?

### ISSUE THREAD

**Issue by Void48** [joelacus/RedditEnhancer#51]
Why does the extension default to a smaller font? Can we please make the default option match what Reddit uses? Thanks

**Comment by joelacus** [comment]
Sorry, I don't quite understand. Which font are you referring to, and on which version of Reddit?
By default, the font resize options are off, but you can use the slider to pick whichever size you want, or slide it all the way left to disable it. When the option is disabled, the font will revert to whatever Reddit's default font size is.

**Comment by joelacus** [comment]
> it fixed itself

Ah that's good then. These are the types of issues I like haha
