### ISSUE TITLE
[BUG] Stuck at loading page when redirect to old new UI in other container in Firefox

### ISSUE THREAD

**Issue by DarkDipper** [joelacus/RedditEnhancer#52]
It seems like when the add-on try to redirect new new UI to old new UI in a container that you never log in to reddit before in Firefox.  It will get stuck at the loop trying to redirect.

Step to reproduce:
1. Setting add-on redirect reddit to old new UI
2. Create/Use a container that you never log in to reddit before to access to reddit

- Browser: Firefox
- Browser version: latest
- Add-on version: latest

**Comment by joelacus** [comment]
Yes, I've noticed this too. Reddit will force a redirect to the New New UI, but then the add-on tries to redirect back, and they end up fighting each other and get stuck in a loop. The only way to resolve this as far as I know, is to login, then it allows you to use the Old New UI :/

**Comment by DarkDipper** [comment]
Then can you not redirect to old new UI when user not log in reddit for now ? Because sometime I access into reddit using "temporary" container to find some solution and just keep them there. I don't want it to mess up algorithm suggestion feed for my account :P

**Comment by joelacus** [comment]
Yes, I'll try to check if the user is logged in, if not, then it won't redirect and will let Reddit use the New New UI. This will be better at least than getting stuck in a loop!

**Comment by vxarctic** [comment]
Same issues

**Comment by joelacus** [comment]
Hi. I've just published version 1.6.0 to fix this. If it detects you are not logged in, because of the container, then it will let Reddit just use the New New UI.
