### ISSUE TITLE
[Feature request] Hide join buttons on New New UI

### ISSUE THREAD

**Issue by georgwacker** [joelacus/RedditEnhancer#53]
When browsing all/popular, every post has a big join button, when you are not subscribed to the sub.

Would be a nice option to hide this button completely.

**Comment by joelacus** [comment]
Hi. Yeah, I can add this to the next version, no problem.

**Comment by joelacus** [comment]
Just published version 1.6.0 with an option to hide the join button on Old New and New New UI :)

**Comment by georgwacker** [comment]
I'm still seeing the join button on /r/all via New New UI.
If I shrink the window horizontally, they disappear at some point. So it is working, but not for larger resolutions.

**Comment by joelacus** [comment]
The resolution shouldn't matter. Maybe my tweak is being overridden by a new site update.

If you know about CSS, this is the current way of hiding the join button:
```
shreddit-post shreddit-join-button {
    display: none;
}
```

I can change it to this. It adds a redundant selector just in case, and forces the "display none" to take priority.
```
shreddit-post shreddit-join-button,
[data-testid="credit-bar-join-button"] {
    display: none !important;
}
```
