### ISSUE TITLE
[Feature request] always show all comments

### ISSUE THREAD

**Issue by rajarshikhatua100** [joelacus/RedditEnhancer#54]
![Screenshot (455)](https://github.com/joelacus/RedditEnhancer/assets/77912617/9fa73fc4-2a49-4be5-b109-76a32b051dad)
reddit shows the "view more comments" botton , I want to auto expand all of the comment. the current version does not have this

**Comment by joelacus** [comment]
Hi. I've just published version 1.7.0 with a new option "Auto Load More Comments". This will load all the comments, however, it will slow down the page a bit and will use more RAM.
