### ISSUE TITLE
Few issues, using new new ui

### ISSUE THREAD

**Issue by eXiGe** [joelacus/RedditEnhancer#55]
Great job on this extension, resize feed/post and removing sidebar was exactly what I was looking for. Which brings the first issue, those modifications are not being applied to sub-comments that open in a new page.

Under hide elements, I didn't see an option to remove TOPICS from the sidemenu for new new UI.

Lastly, changing sidemenu background colour fails to activate, the icon indicator doesn't even change to orange.

Just a few small things honestly, well done with this!

**Comment by joelacus** [comment]
Thanks! I missed the sub-comments page, that's an easy fix. Same with the Topics section in the sidemenu, I think that only shows when you're not logged in, but I can certainly add an option to hide that. The sidemenu background colour option had a simple typo in the code, my bad. I also noticed the sidemenu button hover colour option didn't work either, I kinda forgot to add the code responsible for listening for the input, whoops. 

These are all easy fixes, thanks for letting me know! :)

**Comment by joelacus** [comment]
Hi. I've just published version 1.7.0 with these changes! I noticed there is a new section "Custom Feeds" in the side menu now, so I added an option to hide that as well :)
