### ISSUE TITLE
Firefox cleared cache Old New UI stuck refeshing

### ISSUE THREAD

**Issue by vxarctic** [joelacus/RedditEnhancer#56]
I cleared my cache in Firefox. When enabling Old New UI an error message saying unable to load comes up and the page defaults to old reddit and gets stuck in a refresh loop. If I switch to ALL instead of HOME in Reddit when switching to Old New UI the page loads correctly.

Running Firefox 125.0.1 on Windows 11

**Comment by joelacus** [comment]
Hi. What was the URL you were trying to use when you get the error, just www.reddit.com? Also, were you logged in to your reddit account?

**Comment by vxarctic** [comment]
https://www.reddit.com/

Yes, I was logged into my account.

**Comment by joelacus** [comment]
Sorry, I missed this. I'm not sure what the problem was tbh. Reddit has discontinued the "Old New UI" now anyway, so I guess I can close this issue. If you have any other issues or requests with the latest Reddit, let me know, and I'll try to help.
