### ISSUE TITLE
[Translation] In french 1.7.0

### ISSUE THREAD

**Issue by RedAstaire1** [joelacus/RedditEnhancer#58]
Hide the Custom Feeds Section -> Masquer la section 'Flux personnalisés'
Hide the 'Join' Button On Posts -> Masquer le bouton 'Rejoindre' sur les postes
Auto Load More Comments -> Charger automatiquement plus de commentaire
Post Title -> Titre du poste

Thank you !

**Comment by joelacus** [comment]
Thanks! I forgot to translate these for all the other languages as well, oops.

So is "Post" in French "Poste", not "Publication"? I wasn't sure.

**Comment by RedAstaire1** [comment]
Publication works but is too formal. It's not very important anyway. Poste(s), Post(s), publication(s) works.

After some research, it seems that "Post" works very, very well. In any case, Post and poste being very similar, are understood by the French. Ultimately, you can put "Post" (with capital P) (Posts in plural work too and it will be understood) in place of "poste", it will be very, very well understood, and even better ;). An Anglicime that we (again) borrowed from you.

**Comment by joelacus** [comment]
That's very informative thank you. 

> An Anglicime that we (again) borrowed from you.

Well, we've borrowed a lot of your words, so you can have one of ours :)

**Comment by joelacus** [comment]
I've just published version 1.8.0 with these changes. Thanks again for helping with the translation!
