### ISSUE TITLE
Hide karma doesn't seem to work

### ISSUE THREAD

**Issue by Malvalar** [joelacus/RedditEnhancer#59]
The Hide Karma feature doesn't seem to work on the Old or New reddit on Firefox when I enable it.

Would also be cool if the Hide Karma was added for the New New UI so we could hide the score but keep the ability to vote.

**Comment by joelacus** [comment]
Hi. The hide karma option hides your karma near your username in the upper right for Old and Old New Reddit. New New Reddit doesn't show your karma there anymore. I just tested it and it still works. Is it not for you, even after a page refresh?

**Comment by Malvalar** [comment]
Oh it just hides total karma.
I thought it mean hiding karma everywhere, including posts and comments.

Is that an option?

**Comment by joelacus** [comment]
No, hiding karma on posts and comments is not an option. Is that something you'd find useful?

**Comment by Malvalar** [comment]
Sorry, wrote up a reply and forgot to hit the comment button.

Yes, I think it would be. Personally I'm interested to see how I perceive reddit without being influenced by the scores of posts/comments.

I think people who are interested in hiding the overall karma score might be interested in it as well.

**Comment by joelacus** [comment]
>Sorry, wrote up a reply and forgot to hit the comment button.

No worries.

>Yes, I think it would be. Personally I'm interested to see how I perceive reddit without being influenced by the scores of posts/comments.

I admit I didn't see the point before, but this is an interesting idea actually. I can look into adding this as a new option.

**Comment by Malvalar** [comment]
Cool, thank you.
