### ISSUE TITLE
Change link colour

### ISSUE THREAD

**Issue by placoderm** [joelacus/RedditEnhancer#60]
First off, amazing plugin. Thanks!

My biggest problem with the new new reddit is that the links are coloured almost identically with regular text. So I would love the option to underline links or change their colour. 

One could argue that underlining links is an accessibility issue.

Thanks for considering.

**Comment by joelacus** [comment]
>First off, amazing plugin. Thanks!

Thank you! :)

>My biggest problem with the new new reddit is that the links are coloured almost identically with regular text. So I would love the option to underline links or change their colour.

Are you referring to the links in the post content and comments? They are blue for me, although not underlined in the comments. I can easily add a new option though to change their colour. I could also add an accessibility option to underline all links.

**Comment by placoderm** [comment]
Oh, sorry. Yes, I meant in the text of the comments. I'm not sure exactly what happened to change thing. Maybe it's always been like that and I only noticed because of the most recent re-design.

In any case, not having underlined links, while stylish, is poor accessibility. And I mean links in the body of posts and comments, not that every clickable thing needs to be underlined.

I tried using Stylus to add custom css for the links, but I think the way Reddit is coded prevents Stylus from working.

The UI for your plugin is really good and I appreciate the time you spent doing it.

**Comment by joelacus** [comment]
>The UI for your plugin is really good and I appreciate the time you spent doing it.

Thank you, design is important to me, I'm happy you like it :)

I've just published version 1.8.0 with an option to change the link colour (Style > Theme Colours > Post > at the bottom), and an option in Accessibility to underline the links.

**Comment by placoderm** [comment]
Thanks!!!
