### ISSUE TITLE
[New New UI] Hide NSFW content still showing up 1.7

### ISSUE THREAD

**Issue by gh0sti** [joelacus/RedditEnhancer#62]
New New UI with Hide NSFW content still shows with 1.7.0 using Microsoft Edge.

![image](https://github.com/joelacus/RedditEnhancer/assets/4202657/c0e42bfc-2c89-4907-bd04-1e575422e581)

**Comment by joelacus** [comment]
Does it still not work even after refreshing the page? I can't reproduce the issue myself, but I've added another way for extension code to select the nsfw posts and hide them.

**Comment by gh0sti** [comment]
I just remember with the older new UI that blocking nsfw content would happen automatically without having to reload the page. It does remove the content once I reload website on 1.7.0
