### ISSUE TITLE
[BUG - Old New Reddit & New New Reddit] Wiki page content not expanding to match styling size

### ISSUE THREAD

**Issue by TheCodingCarson** [joelacus/RedditEnhancer#64]
**Bug:** Wiki pages for sub reddit's aren't following the styling that is set in the extension for any version of reddit other then old reddit, photo included for reference.

![Screenshot 2024-05-20 163705](https://github.com/joelacus/RedditEnhancer/assets/114391166/3fb72dce-4a76-4a5d-b2b2-3572663cb4bf)

**Potential Fix:** By changing the "max-width" value for "`@media (min-width: 1392px)`" for id "main-content" with class "`main w-full flex-grid--main-container-card right-sidebar-s`" from "`max-width: 756px;`" to "`max-width: var(--re-sub-width) !important;`" it follows the styling set in the extension, photo below again for reference.

![Screenshot 2024-05-20 164405](https://github.com/joelacus/RedditEnhancer/assets/114391166/6941470e-2ebf-4e94-82c3-ab12b4fb5df7)

**Tested:** Only tested on Google Chrome.

**Extra Note:** I have enabled "Remove the Page Side Margin" and "Hide Interface Gaps".

Please let me know if I can be of any other help for this bug!

**Comment by joelacus** [comment]
I missed these Wiki pages, thanks for letting me know, and providing the extra information.
This will be fixed in version 1.9.0!
