### ISSUE TITLE
[Feature Request] Sperate Color Customization for Search Bar (Both unfocused and focused, plus dropdown)

### ISSUE THREAD

**Issue by TheCodingCarson** [joelacus/RedditEnhancer#65]
**Feature Request:** Adding a option to customize the search bar color, I personally use the search bar set to transparent and can't see search results very well and think it would help a lot with that.

**Current Browser:** I'm currently using Google Chrome and haven't tested to see if it does change in other browsers.

**Potential Implementation Idea:** For the style of "`header, #user-drawer-content`" change "`--color-neutral-background-strong: var(--re-theme-header-bg);`" to add an "`--color-neutral-background-strong: var(--re-theme-header-search-bg);`" that can be adjusted and also adding it to the style for the "`<reddit-search-large>`" div to allow changing the unfocused color in the extension allowing for a custom search bar and dropdown color.

Also I would like to say thank you for your work on making and maintaining this extension I use it both on Chrome and Firefox and it makes Reddit a much better experience all around!

**Comment by joelacus** [comment]
>Also I would like to say thank you for your work on making and maintaining this extension I use it both on Chrome and Firefox and it makes Reddit a much better experience all around!

You're welcome. I appreciate this, thank you :)

I can certainly add this feature, no problem. It'll be in the next version (1.9.0).

**Comment by joelacus** [comment]
Hi, I've just published version 1.9.0! Let me know if you have any other issues, thanks :)
