### ISSUE TITLE
Bug: 'Old New UI' Redirect is delayed 

### ISSUE THREAD

**Issue by sliceanddice9** [joelacus/RedditEnhancer#66]
When I launch the Reddit website I am greeted with the 'New New UI'. It normally takes  a good 3 or 4 seconds before the built-in redirect function takes me to my preferred version of the Reddit UI which is the 'Old New UI'.

I'm having to use **'Reddit UI Redirector'** for Firefox, and  **'Change Reddit Interface - RedChanger'** for Microsoft Edge which are separate add-ons that enable the 'Old New UI' to open instantly.  

It's happening on the website with Firefox, and with the website on Microsoft Edge. Although with Microsoft Edge it's slightly different since with Microsoft Edge the issue with the delayed redirect only happens when actually opening a notification.

**Comment by joelacus** [comment]
This is a good point. It's something I've been wanting to improve actually. The current method just uses some javascript once the page starts to load to determine if the page needs to be redirected or not. Another way would be to be use "declarativeNetRequest" to redirect certain URLs. This would work faster, but would require the "declarativeNetRequest" permission. I'll try to implement it for the next version.

**Comment by joelacus** [comment]
Hi. I've just published version 1.10.0. You'll need to allow the new permission once it updates.
It feels much better in my testing. Let me know how it goes and if you have any issues! :)

**Comment by sliceanddice9** [comment]
> Hi. I've just published version 1.10.0. You'll need to allow the new permission once it updates. It feels much better in my testing. Let me know how it goes and if you have any issues! :)

The redirect to the 'Old New UI' is much quicker and snappier now, thanks for the update!
