### ISSUE TITLE
[Feature Request] Save the hidden state of sidebar expansion panels

### ISSUE THREAD

**Issue by Void48** [joelacus/RedditEnhancer#68]
I don't like seeing all the subreddits and information from the expansion panels. It clutters up the Reddit homepage, and I think it would be a great quality-of-life improvement if their state could be saved so that if I **hide them**, they would **stay hidden** even after refreshing the site. Also appreciate the work being done to the extension! 

![image](https://github.com/joelacus/RedditEnhancer/assets/85196642/b9930a7f-2ab5-45a3-9151-118a30938178)

**Comment by joelacus** [comment]
Hi. Yeah, I can certainly look into adding an option to save the current state of the panels, I'm surprised Reddit doesn't already save them. If you just want to permanently hide a certain section however, I've already added options for that.

**Comment by joelacus** [comment]
Hi, yes, sorry, I get distracted. I'll try to add it into the next update :)

**Comment by joelacus** [comment]
I've just published version 1.12.0 with an option to remember the hidden states :)
You can enable it here (Productivity > Side Menu).
