### ISSUE TITLE
v1.1.0 update doesnt work correctly

### ISSUE THREAD

**Issue by burd1** [joelacus/RedditEnhancer#69]
Before the update the site redirection would take time, but it would load the "Old New UI" eventually, now it does nothing if i click on posts and stuff from google. If i go directly to reddit it works correctly though, so basically external links dont use the setting correctly?

**Comment by burd1** [comment]
Odd, it seems like it just randomly starting working now, i dont know how that works but will monitor it for a while.

**Comment by joelacus** [comment]
I'm not quite sure why it didn't work to begin with, maybe the google tab had to be refreshed after the update to be detected? Anyway, I'm glad it works now. Please let me know if you find any issues. Thanks!

**Comment by burd1** [comment]
> I'm not quite sure why it didn't work to begin with, maybe the google tab had to be refreshed after the update to be detected? Anyway, I'm glad it works now. Please let me know if you find any issues. Thanks!

I had refreshed the entire browser and all the tabs, it just didn't work at that time, seems to be fine now, earlier i got an error 503 if i recollect correctly, then that fixed up too. I will let you know if any other issues arise, thank you for this great extension.
