### ISSUE TITLE
Prevents Reddit from opening in Firefox 127 (Fedora 40 Linux)

### ISSUE THREAD

**Issue by ItsRogueRen** [joelacus/RedditEnhancer#72]
When the add-on is enabled, Reddit fails to open with an error saying

"The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

  -  This problem can sometimes be caused by disabling or refusing to accept cookies."

When I disable the add-on, everything loads like normal with 0 issues.

**Comment by joelacus** [comment]
Hi. This is normal unfortunately if you are not logged in to Reddit and are trying to use new.reddit.com (Old New UI).
They force redirect people who aren't logged in to the latest version of the site, which conflicts with the addon redirect feature. You either have to login, or not use the redirect feature to Old New UI.

I don't think there is anything I can do about this :/

**Comment by ItsRogueRen** [comment]
> Hi. This is normal unfortunately if you are not logged in to Reddit and are trying to use new.reddit.com (Old New UI).
> They force redirect people who aren't logged in to the latest version of the site, which conflicts with the addon redirect feature. You either have to login, or not use the redirect feature to Old New UI.
> 
> I don't think there is anything I can do about this :/

could a workaround be added where it opens with old if it sees you aren't logged in? Just so reddit is at least reachable

**Comment by joelacus** [comment]
That would be ideal, but the redirect happens before the page even starts to load, so I'm not sure how I can detect if the user is logged in or not to be honest. I could add a warning though in the popup when you select "Old New UI", so you can at least expect the error.

**Comment by joelacus** [comment]
I've just published version 1.10.2. I've added a warning message when you select "Old New UI" for the redirect saying that you must be logged in to Reddit for it to work. This is the best I can do for now I'm afraid.
