### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by lylesnake** [joelacus/RedditEnhancer#75]
Hi there. I wanted to let you know that the extension does not appear to be working in Firefox anymore. It used to work easily and beautifully, but now none of the custom toggles I have appear. I'm not sure what changed. Let me know if you need more info. Thanks!

**Comment by joelacus** [comment]
Hi. Has it just not restored your previous settings, but still works if you re-enable the options again?

The settings are saved in your browser, so if you have cleared or reset your Firefox profile, it could wipe any extension saves if you don't have browser sync enabled. If you haven't cleared anything and/or have browser sync enabled, I'm not sure what could have happened to be honest.

If you can re-enable the options and it works again, I'm afraid your previous saved settings may be lost.
I added a config backup and restore function in the extension settings in case something like this happens.

Sorry for the inconvenience :/
