### ISSUE TITLE
Feature Request: Make Side Menu Width More Adjustable On 'New New UI'

### ISSUE THREAD

**Issue by sliceanddice9** [joelacus/RedditEnhancer#77]
Unfortunately by default the Side Menu in the 'New New UI' takes up a fair amount of room. I know you can remove the Side Menu all together, but doing that takes away important things (like access to 'Communities') which I happen to find very important.

If the Side Menu's Width could be adjustable so that it can be horizontally shifted more to the left of screen so that the main attraction itself, which is obviously the actual Home Feed, can be expanded even more in the center of the page then that will be an improvement IMO.

**Comment by joelacus** [comment]
Adjusting the side menu and the side bar width is actually on my to-do list, so yeah, I'll add this at some point.

I'm not sure what you mean though about the side menu being shifted more to the left of the screen, isn't it already fixed at the left side for you?

**Comment by sliceanddice9** [comment]
> Adjusting the side menu and the side bar width is actually on my to-do list, so yeah, I'll add this at some point.
> 
> I'm not sure what you mean though about the side menu being shifted more to the left of the screen, isn't it already fixed at the left side for you?

It is toward the left side by default yes. I guess I just mean have the Side Menu shrunk down or scaled down so that it doesn't occupy as many pixels as it currently DOES. Glad to know it is on your to do list man. 👌

The Side Menu, which includes 'Communties', is just one of many reasons why the 'Old New UI' is so much better vs the 'New New UI' because in the 'Old New UI' the 'Communities' section could be "hidden" within a drop down menu, so the 'Communities' were still directly accessible, where as you can't do the same thing on the 'New New UI' with the 'Communities'. I like having direct, easy access to 'Communities' without the actual list of 'Communities' themselves taking up a lot of space.

I know the 'Old New UI' is still working but like you said in the other thread - the 'Old New UI' might not have a lot of time left. 😕

**Comment by joelacus** [comment]
> The Side Menu, which includes 'Communties', is just one of many reasons why the 'Old New UI' is so much better vs the 'New New UI' because in the 'Old New UI' the 'Communities' section could be "hidden" within a drop down menu, meaning the 'Communities' were still directly accessible without being on-screen at all times. Unfortunately you can't do the same thing on the 'New New UI' with the 'Communities'.

Not yet ;) I added an option to modernise the Old UI to make it look more like the Old New UI, and I added a dropdown menu at the top for the list of joined subreddits. I could do something similar perhaps for the New New UI.

> if you click a subreddit and then go back to the home page - the 'Communities' are back on-screen, so they don't even stay "hidden" anyway.

Someone else has mentioned this as well, I'm surprised Reddit doesn't already remember which section is hidden or not. I'll see what I can do about this.

> Your Reddit Enhancer add-on definitely makes the 'New New UI' at least bearable.

Thanks. I've been a bit busy lately, but I'll work on a new update soon :)

**Comment by sliceanddice9** [comment]
> > The Side Menu, which includes 'Communties', is just one of many reasons why the 'Old New UI' is so much better vs the 'New New UI' because in the 'Old New UI' the 'Communities' section could be "hidden" within a drop down menu, meaning the 'Communities' were still directly accessible without being on-screen at all times. Unfortunately you can't do the same thing on the 'New New UI' with the 'Communities'.
> 
> Not yet ;) I added an option to modernise the Old UI to make it look more like the Old New UI, and I added a dropdown menu at the top for the list of joined subreddits. I could do something similar perhaps for the New New UI.
> 
> > if you click a subreddit and then go back to the home page - the 'Communities' are back on-screen, so they don't even stay "hidden" anyway.
> 
> Someone else has mentioned this as well, I'm surprised Reddit doesn't already remember which section is hidden or not. I'll see what I can do about this.
> 
> > Your Reddit Enhancer add-on definitely makes the 'New New UI' at least bearable.
> 
> Thanks. I've been a bit busy lately, but I'll work on a new update soon :)

Yes on the home page of the 'New New UI' that would be amazing if you could add a dropdown menu next to the main Reddit logo and 'Search Reddit' search box that features a list of all the Subreddits/Communities that you've joined, all your "Favorite" Subreddits/Communities, and even the individual Reddit users that you 'Follow" as well, but if your not able to add "Favorites" or "Following" to the dropdown menu than just the actual Subreddits/Communities themselves will be fine (just like the 'Old New UI' and your version of the 'Old Old UI'.)  😀

If you add the dropdown menu to the 'New New UI' that will also have the flow on benefit of being able to safely activate the 'Hide the Side Menu' switch in the Reddit Enhancer settings which looks much better. 

Really appreciate your hard work man, people like you make Reddit a better place for everyone.

**Comment by joelacus** [comment]
Hi. I've just published version 1.11.0 with an option to change the side menu width (Productivity > Side Menu > Side Menu Width). You can set the width between 200 - 300px. Smaller than 200px would start to break the layout of the elements in the side menu.

I've not yet added a dropdown menu option, but I've added two other options you may like:
(Hide Elements > Side Menu > Show Side Menu Toggle Button) This adds a button at the top of the side menu to hide it and show it whenever you want.
(Hide Elements > Side Menu > Side Menu Icons Only) Hides all the text and just shows the icons.

> add a dropdown menu next to the main Reddit logo and 'Search Reddit' search box that features a list of all the Subreddits/Communities that you've joined, all your "Favorite" Subreddits/Communities, and even the individual Reddit users that you 'Follow" as well

I don't think I can add favourited subreddits and followed users to be honest, it would basically just be the current side menu in a different place.

> Really appreciate your hard work man, people like you make Reddit a better place for everyone.

Thank you for this, I'm happy you like the extension :)
