### ISSUE TITLE
Add a comment section gets sticky

### ISSUE THREAD

**Issue by 4NXIE7Y** [joelacus/RedditEnhancer#79]
When using a styling element for the post background color it makes the add a comment section sticky when viewing an image.

https://github.com/user-attachments/assets/79c96478-baa6-4580-b4e7-e88fda40f052

**Comment by joelacus** [comment]
Thanks for the video. I think I found the issue, it should be fixed in the next version.

**Comment by joelacus** [comment]
I've just published version 1.11.0 with a fix. Let me know if you have any other issues, thanks!
