### ISSUE TITLE
[Feature Request] Scrollbar to text posts

### ISSUE THREAD

**Issue by DallasBelt** [joelacus/RedditEnhancer#8]
Just like the scrollbar to tall images, could it be possible to add a scrollbar to text posts?
Also, could it be possible to hide the "See full image" button?

Thanks!

**Comment by joelacus** [comment]
Hi. Adding a scrollbar to a long text post is possible, however there is a limit to the amount of content on the post on the feed, and you'd have to click on the post to read the end if it's too long :/
In this example, the blue area shows the extra content you'd be able to scroll to, but the red area doesn't exist on the post on the feed. I can still add this as an option though so you can read a bit more.

![image](https://user-images.githubusercontent.com/43767965/230734173-4c653461-5c63-4c39-b274-00da9221cc7d.png)

I can add an option to hide the "See full image" button :)

**Comment by DallasBelt** [comment]
@joelacus THANKS A LOT! I appreciate your excellent work on this extension/add-on. Looking forward to test the new features :D

**Comment by joelacus** [comment]
Hi. I've just published 0.10.0, it's available now for Firefox, but Chrome and Edge will take about a week to be verified. The option to scroll on long text posts should be enabled by default, but you will need to toggle on the option to hide the "See full image" button (It's under the image options). 

Let me know how it goes :)

**Comment by DallasBelt** [comment]
Awesome! It's working as expected! Thanks a lot :D
