### ISSUE TITLE
Show Post Author on the Home Feed not working

### ISSUE THREAD

**Issue by minkses** [joelacus/RedditEnhancer#80]
The option to show post author on the home feed isn't working for me on the new new UI. If any other info is needed, I'll gladly provide it.

Also, love your work!

**Comment by joelacus** [comment]
Sorry about that. It still works for me, maybe Reddit is testing different versions and something broke it.
Has it worked before and now just stopped? 

>  If any other info is needed, I'll gladly provide it.

Thanks. I'm just finishing up some new features for the next update at the moment, but yes, I may need your help to figure out what's wrong.

> Also, love your work!

I appreciate that, thank you! <3

**Comment by minkses** [comment]
While writing my reply here and messing around to see if I could possibly gain more relevant info, I figured out that it _does_ show in card view, just not in compact view. I hope that that's useful and thank you so much for your time!!

**Comment by joelacus** [comment]
Oh that's great, thanks. Yeah I completely forgot about compact view, my bad. I'm glad it works in card view at least. I'll try and make it work for the compact view in this next update.

**Comment by minkses** [comment]
I appreciate it a lot!!

**Comment by joelacus** [comment]
Hi. I've just published version 1.11.0 with this fix. Let me know if you have any other issues, thanks!
