### ISSUE TITLE
[Bug: New New UI] 'Hide the Recent Section' not working

### ISSUE THREAD

**Issue by ingyrid** [joelacus/RedditEnhancer#81]
![recentposts](https://github.com/user-attachments/assets/35926a8b-2304-4d47-98c5-fbc703f3f0d6)

I have 'Hide the Recent Section' enabled on New New UI on Firefox and it's still displaying. Please let me know if there's any information I can provide to better diagnose this issue.

Thank you for your hard work--it makes browsing Reddit a much nicer experience.

**Comment by joelacus** [comment]
The "Hide the Recent Section" option refers to the recent sub reddit section in the left side menu. Sorry for the confusion.
The next version I'm currently working on actually has an option to hide the recent posts in the side bar.
I'll release the update soon.

> Thank you for your hard work--it makes browsing Reddit a much nicer experience.

Thank you, I'm happy to hear that :)

**Comment by joelacus** [comment]
I've just published version 1.11.0 with this feature. You can enable the option here:
Hide Elements > Sidebar > Hide Recent Posts
