### ISSUE TITLE
Feature Request: for sh.reddit.com Expand the post fully like old and new new reddit. 

### ISSUE THREAD

**Issue by dnet890** [joelacus/RedditEnhancer#82]
Hi
I see the version 1.11.0 and it is really nice we can toggle the side menu to hide it. But, when we hide the side menu or the side menu is totally hidden or show the toggle button. Is it possible to make the thread or the post expand fully like old reddit or new.reddit?

**Comment by joelacus** [comment]
I'm not sure what you mean. Resizing the feed/post to 100% will use up all available space that isn't used by the side menu.

**Comment by dnet890** [comment]
yeah you are right thanks
