### ISSUE TITLE
(Bug) New update for Reddit Enhancer broke Internal Reddit Search and submit new post

### ISSUE THREAD

**Issue by dnet890** [joelacus/RedditEnhancer#84]
Hi
I know reddit enhancer have new update recently and it seems that it broke reddit internal search and submit new post and also parts of old reddit like old.reddit.com/prefs/apps/ unless I disabled the extension. What do you think?

**Comment by joelacus** [comment]
Interesting, the update shouldn't have affected these features. Were they working fine on the previous version?
How are they broken exactly? Are you able to provide any screenshots of the issues?

**Comment by dnet890** [comment]
Yeah, on previous version it is working well and for this version. it just stop loading and I got this error
![2024-09-18_23-38](https://github.com/user-attachments/assets/1b58f95f-7544-4813-9b92-1acac1996804)

**Comment by dnet890** [comment]
on previous version it just works and I got error on this current version like this
![image](https://github.com/user-attachments/assets/c0305c3e-faff-4abe-ad86-8f820183414e)

**Comment by joelacus** [comment]
Is it just the reddit search and create new post on old.reddit.com, or does it affect the newer versions?
Could you provide any more URLs of the broken pages, it might help me identify the issue. Thanks.

**Comment by dnet890** [comment]
@joelacus it looks like I found the culprit that by disable this setting cause the problem solved properly. But, I don't think it is feasible for long term
![image](https://github.com/user-attachments/assets/6b06cd3e-04f7-4d99-a802-7b345c26fa00)

**Comment by joelacus** [comment]
Ah yes, this is it! I enabled this and got the same page errors. I don't know why I didn't think of trying this before. I found and fixed the issue!

**Comment by LetsPlayNintendoITA2023** [comment]
it breaks new posting on new reddit es

**Comment by joelacus** [comment]
Hi. Sorry for the delay. I've just published version 1.12.0 with a fix for this.
Let me know if you find any other issues, thanks :)

**Comment by dnet890** [comment]
@joelacus we can create a new post now. But, again when I want to search something on the Reddit searchbar. it does not worked https://www.reddit.com/r/pcgaming/search/new?q=friend&cId=a3a166ac-6798-4df8-b12d-b8e7860a02b9&iId=d68412f6-d75c-4c6d-87f1-13135cb9a720

<img width="532" alt="image" src="https://github.com/user-attachments/assets/6f1f4c32-bf0b-4ef4-b733-7db4c68e09a1">
