### ISSUE TITLE
Feature Request: new ui Sidebar Community "auto-collapse" instead of hiding

### ISSUE THREAD

**Issue by SilberComic** [joelacus/RedditEnhancer#86]
hi there, i have alot of communities muted since they are very active and i dont want my feed to be spammed with it.
It would be nice to have the community sidebar be autocollapsing (As there are some that dont need to be seen by others when screensharing or something) rather than hiding it completely.

**Comment by joelacus** [comment]
Hi. So would you want something similar to the "Show Side Menu Toggle Button" feature, but for the sidebar, where you can click a button to show/hide the sidebar?

**Comment by SilberComic** [comment]
i didnt see that feature yet (and cant test rn since im on vacation) but its probably what i mean ^^" if you have nothing disabled in the new ui the tabs on the left woth communities, recents and stuff have little arrows next to them to collapse them for the session, i want them collapsed everytime without clicking

**Comment by joelacus** [comment]
Oh I misunderstood sorry, I thought you meant the right sidebar on subreddits, you mean this:

![image](https://github.com/user-attachments/assets/c88d8b7b-5bfc-4617-8cb5-f3692054abaa)

I have on my to-do-list a feature to remember the open/closed state of those collapsible sections, so when you open a new page, it will auto collapse them, or not. I'm going on holiday too next week, but I'll work on it when I get back.

**Comment by SilberComic** [comment]
yep ment the sidebar of reddit itself not the sub ^^ alright have a nice holiday c:

**Comment by joelacus** [comment]
Hi! I've just published version 1.12.0 with an option to remember the open/closed states of those sections in the left side menu. You can enable it here (Productivity > Side Menu). You should get the update automatically soon :)

**Comment by SilberComic** [comment]
Hi! It's been working fine since you added this feature, but I wanted to ask if there's a way to stop it from showing the communities before collapsing or going to the remembered setting. It's flashing them for a short time before doing that.  For example, there are some communities that don't need to be shared when sharing the screen.
