### ISSUE TITLE
On Extension v1.12 Reddit Internal Searchbar is broken on subreddit unless I disable default feed sort option

### ISSUE THREAD

**Issue by dnet890** [joelacus/RedditEnhancer#89]
Hi
I know that searchbar is completely broken before update 1.1.2 and after Extension update, it is getting better. But, it seems the searchbar is completely broken on subreddits unless I disable the default feed sort option. What do you think?
[2024-10-21 09-31-58.mp4.zip](https://github.com/user-attachments/files/17452668/2024-10-21.09-31-58.mp4.zip)

**Comment by joelacus** [comment]
Ah the subreddit search bar, I didn't test that one. Thanks for letting me know.
I've fixed it now. I'll release the update soon.
