### ISSUE TITLE
[Feature Request] Open Links To Posts In New Tab

### ISSUE THREAD

**Issue by sliceanddice9** [joelacus/RedditEnhancer#9]
Much like the existing functionality of having new tabs open when clicking on actual sub reddit communities from the home frontpage.

**Comment by joelacus** [comment]
Hi. Yeah I can add this :)

**Comment by joelacus** [comment]
I've just published version 0.15.0 with this feature. Chrome and Edge will take about a week until the update is available, but it's out now for Firefox :)

**Comment by sliceanddice9** [comment]
Thank you, the function works well most of the time, but I have observed that occasionally posts don't always open in their own tab.

**Comment by joelacus** [comment]
Thanks for the feedback :) I'll look into why it sometimes doesn't work.

**Comment by joelacus** [comment]
Hi. I've just found an option in the reddit profile settings to open posts in a new tab haha. I don't know how long it's been there, but that should work more reliably than my solution. Go to [reddit.com/settings/feed](https://www.reddit.com/settings/feed) and enable "Open posts in new tab" near the bottom. I'll probably remove this feature from the extension and replace it with a notice about this option.

**Comment by sliceanddice9** [comment]
> Hi. I've just found an option in the reddit profile settings to open posts in a new tab haha. I don't know how long it's been there, but that should work more reliably than my solution. Go to [reddit.com/settings/feed](https://www.reddit.com/settings/feed) and enable "Open posts in new tab" near the bottom. I'll probably remove this feature from the extension and replace it with a notice about this option.

Thanks for the heads up. I didn't know the **'Open Links To Posts In New Tab'** feature was a default built-in feature within _Reddit_ itself. However I still think your implementation of **'Open Links To Posts In New Tab'** is important to keep inside the _'Reddit Enhancer'_ add-on because with your version of  **'Open Links To Posts In New Tab'** I can choose to keep the feature enabled using the _Reddit_ site in one web browser while keeping it disabled in the _Reddit_ site using another web browser. 

With the default built-in feature of **'Open Links To Posts In New Tab'** in [reddit.com/settings/feed](https://www.reddit.com/settings/feed) - the setting once enabled is universally triggered on all web browsers you use the _Reddit_ website on with the same account. 

So I hope you reconsider and keep your version of  **'Open Links To Posts In New Tab'** alive in the _'Reddit Enhancer'_ add-on, even if it is imperfect. It works more often then not. :)

**Comment by joelacus** [comment]
You make a good point, I do like options and flexibility. I'll keep it in, and I'll try to improve it when I have some time :)
