### ISSUE TITLE
Post titles have abnormally large font in compact mode

### ISSUE THREAD

**Issue by timebomb0** [joelacus/RedditEnhancer#91]
As of November 11th, my home page and subreddit feeds are all showing the post title as having very large font. This is only on compact mode. The extension is working great otherwise, thanks for all the hard work.

With the extension:
![image](https://github.com/user-attachments/assets/ee10809d-65eb-489d-b3ca-f8af5e26db49)

Without the extension:
![image](https://github.com/user-attachments/assets/dd342a52-68b1-460b-b249-03744128c3a0)

**Comment by joelacus** [comment]
Hi. So is the font normal sized in card view, and is the "Resize Post Title" not enabled in Accessibility?

**Comment by timebomb0** [comment]
Font sizes are normal on some cards but similarly oversized on other cards. Seems like full image cards have oversized fonts, other cards do not:
![image](https://github.com/user-attachments/assets/6531f15d-da72-4fef-addf-9ca7aaf7e5c9)

Resize font and other accessibility settings are disabled:
![image](https://github.com/user-attachments/assets/571c020b-b0aa-4d78-81a7-6cffbd7f6019)

**Comment by joelacus** [comment]
I made a typo in the code, whoops. This should be fixed in the next version.
