### ISSUE TITLE
The page is not redirecting properly - reddit can't load when RedditEnhancer is activated

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [joelacus/RedditEnhancer#93]
Hi, I'm new to this so I hope I got things OK with this report,

Reddit (I was not with oldreddit) was working until a few hours ago, but, now, I got this: https://imgur.com/a/odglsCZ

I know it's in French, but it's a well-known error message, "the page isn't redirecting properly", as if there's an unending loop for some reasons.

Firefox 133.0.3 (64 bits)
Reddit Enhancer 1.12.1

The extension has a ton of options, I don't know how to export them in case it matters, though, sorry!

If more info is needed, just tell me where I may fetch it, I don't mind. Cheers, and thanks for the great ext!

**Comment by joelacus** [comment]
Hi, thanks for letting me know.

It seems that Reddit is now redirecting more people away from new.reddit.com (Old New UI) to www.reddit.com (the latest version of the website). This will conflict with the extension as it tries to redirect you back to new.reddit.com, causing a loop and a page error. I've just tested this myself and it no longer works for me either :(

Unfortunately, there is nothing I can do about this, sorry. This is something I've been expecting Reddit to do for a while.

You will either have to disable the redirect feature in the extension (top right dropdown menu) and use the latest version of the website, or redirect to the Old version of Reddit.

I don't need your options thanks, but just so you know, you can export them here:
(Settings > Backup) or en française (Paramètres > Sauvegarde)

>  I'm new to this so I hope I got things OK with this report

This was a great report, thank you :)
