### ISSUE TITLE
Accessibility Feature Request - 'Post Comments/Content' needs an adjustable slider setting to make the text thicker thereby making it easier to read.

### ISSUE THREAD

**Issue by leryeo** [joelacus/RedditEnhancer#94]
I find it much more comfortable to read the text on Reddit when the text is thicker, especially the comments section.

I want a feature that adjusts the text's thickness. For example, I prefer the thickness when 'Bionic Reader for Comments' is enabled as I find it far easier to read.

It would be great if we had an adjustable slider for this setting.

**Comment by leryeo** [comment]
The bold isn't essential, as long as one is able to change the weight thereby making it easier to read. Maybe have a few sliders so e.g. post title & text change font weight, post comments change font weight.

Is there any chance of implementing another reader mode other than Bionic Reader? I wish to have something where all letters are highlighted, unlike Bionic which has concise parts of the letters highlighted.

**Comment by joelacus** [comment]
Yes, I could add a few sliders for different text, like the resize font options.

The highlighted parts of the bionic reader text are just bold, so changing the font weight to something bold would have the same effect.

**Comment by leryeo** [comment]
Also would it be possible to increase the font size and change its colour for when you create a post? Currently I find the Title and Body text too small to read.

**Comment by joelacus** [comment]
I've just published version 1.13.0 with options to change the create post font sizes, as well as added options to change the font weight. The default Reddit font uses a weight of 600 or 700 for bold text. I plan to add an option to allow custom fonts which could support more font weights in a future update.

**Comment by leryeo** [comment]
Hi,

The new update is working great, I appreciate all your efforts! I was
wondering if it would be possible to increase the line spacing as I find
hard to read with the current line spacing? If there is a workaround
currently available then please let me know.

Best,

James
