### ISSUE TITLE
Long letters cut off when resizing post titles

### ISSUE THREAD

**Issue by Palletin** [joelacus/RedditEnhancer#97]
Hi, long letters in post titles (g, j, p, etc) are cut off vertically in compact feed view when reducing title font size (I'm using 16px). Thank you for this extension, it improves the default new new UI a lot.
![image](https://github.com/user-attachments/assets/754c1961-7981-40d3-9c6a-cfa1104b2d8b)

If it's possible, separate options for resizing titles in feed view and post view would be great too. Thank you!

**Comment by Palletin** [comment]
ETA: I just noticed that without the extension, in the default new UI the letters are cut off in post view. But not in compact feed view. 
![image](https://github.com/user-attachments/assets/702fc3b3-f983-4ffb-90bc-59e652e88343)

**Comment by sliceanddice9** [comment]
Yeah, the letters being cutoff for post titles is a default bug with the New New UI itself.

**Comment by joelacus** [comment]
Good spot. I've looked into it and the post title element uses the CSS attribute "overflow: hidden" by default, not sure why.

I've added "overflow: unset" to the extension code for the post title and it fixes this clipping issue.

**Comment by joelacus** [comment]
This is fixed in version 1.13.0.

**Comment by Domiran** [comment]
![image](https://github.com/user-attachments/assets/0223182e-d67a-45fc-b325-2ebdff859ca3)

This can still be ever slightly cut off, depending on the font size. At 15 it's ok. 16 and 17 it appears like the picture. At 18 it's ok. At 20 it's particularly bad again.

![image](https://github.com/user-attachments/assets/67305fe4-fd5f-4dca-aa32-2dbeec391466)

To be honest I think I'd just prefer a line height slider.
