### ISSUE TITLE
Font Size Change is not reflected on Profile page in new new reddit. 

### ISSUE THREAD

**Issue by dnet890** [joelacus/RedditEnhancer#99]
Hi
I want to enlarge the font size. But, when I want to go my profile page. The font size for text content  is not changed at all. What do you think?
![2024-12-12_18-17](https://github.com/user-attachments/assets/21d78ee3-f69c-45e9-a8c6-727b470bf1bb)

**Comment by joelacus** [comment]
Hi. Thanks for pointing this out, I hadn't noticed. This will be fixed in the next version.

**Comment by joelacus** [comment]
I've separated the post title and content options for posts in feeds and post pages.
The new options "Feed Post: Title" and "Feed Post: Content" will apply to the profile feed, as well as the home and sub feeds.
